import numpy as np
import matplotlib.pyplot as plt

# # a)
# fun = lambda t : np.sin(800*np.pi*t)
# x = np.linspace(0, 0.1, 1600)
# y = np.vectorize(fun)(x)
# plt.stem(x, y)
# plt.plot(x, y)
# plt.savefig(fname='ex2fig1.pdf')
# plt.show()

# # b)
# fun = lambda t : np.sin(1600*np.pi*t)
# x = np.linspace(0, 3, 12800)
# y = np.vectorize(fun)(x)
# plt.stem(x, y)
# plt.plot(x, y)
# plt.savefig(fname='ex2fig2.pdf')
# plt.show()

# # c) 
# fun = lambda t : np.mod(t, 1/240)
# x = np.linspace(0, 0.1, 1000)
# y = np.vectorize(fun)(x)
# plt.stem(x, y)
# plt.plot(x, y)
# plt.savefig(fname='ex2fig3.pdf')
# plt.show()

# d) 
fun = lambda t : np.sign(np.sin(600*np.pi*t))
x = np.linspace(0, 0.1, 1000)
y = np.vectorize(fun)(x)
plt.stem(x, y)
plt.plot(x, y)
plt.savefig(fname='ex2fig4.pdf')
plt.show()

# e)
x = np.random.rand(128, 128)
plt.imshow(x)
plt.savefig(fname='ex2fig5.pdf')
plt.show()

# f)
x = np.linspace(0, 1, 128*128)
x = np.reshape(x, (128, 128))
print(x[0, :])
plt.imshow(x)
plt.savefig(fname='ex2fig6.pdf')
plt.show()